### PR TITLE
Restrict image to non-root user

### LINKED ISSUE #16: User root
Should be restricted to not run as root

### PR DESCRIPTION
**Pull request by cdenneen**
Fixes #16

### CODE REVIEW

**Comment by nkanderson** [comment]
Hi @cdenneen, thanks for the PR. Based on the use cases we know of, I don't think `sudo` capabilities for the `pdk` user would be necessary. (Docker also recommends avoiding reliance on `sudo` in their [Dockerfile best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user).)

They also recommend using an explicit UID and GID. I'm thinking something like the following may be sufficient in that first `RUN` command:
```
groupadd -g 999 pdk && \
useradd -mr -u 999 -g pdk pdk && \
```

What do you think?

**Comment by da-ar** [comment]
As per @nkanderson comments - i've pushed up changes to use gosu

Screen grab showing pdk running with the PDK user

Screen Shot 2021-04-19 at 11 05 29 AM

**Review by sanfrancrisko — APPROVED** [review]

**Comment by sanfrancrisko** [comment]
We're suspecting this PR might have something to do with the issues you're seeing: https://github.com/puppetlabs/pdk-docker/pull/24

We'll take a look at this. For now, I see you pinned to 2.1.0.0 (https://github.com/puppetlabs/pdk-templates/pull/430), which can probably act as a workaround for now, hopefully?

**Comment by cdenneen** [comment]
@sanfrancrisko seems like puppetlabs/pdk-templates#430 was your commit changing from `nightly` to `2.1.0.0` not me.

**Comment by cdenneen** [comment]
Also the reason for the "sudo" requirements here were more for running docker-in-docker which was part of an additional PR. I do not believe pdk needs to have sudo privileges otherwise. Believe just adding the user and changing to user `USER pdk` should be sufficient without needed to add `gosu` or any other sudo parts.

**Comment by jpogran** [comment]
@cdenneen Ciaran was referring to Paula and mistyped. After this change, our module release jobs (which use this docker image) were unable to build puppet modules in Github. We're still investigating, but we think it's this change here that changed what permissions are used to create files and folders. We're looking into whether we'll be reverting this PR entirely or modifying it to use `USER`.

**Pull request merged**
