### PR TITLE
Updates for running as non-root user, docker for ci use, onceover fix

### LINKED ISSUE #18: Onceover install fails
```
Processing triggers for libc-bin (2.27-3ubuntu1.2) ...
ERROR:  Error installing onceover:
	The last version of cri (>= 2.15.10, < 3.0.0) to support your Ruby & RubyGems was 2.15.10. Try installing it with `gem install cri -v 2.15.10` and then running the current command again
	cri requires Ruby version >= 2.5. The current ruby version is 2.4.10.364.
```
Issue is the installer is grabbing the 2.4.10 ruby directory instead of 2.5 or 2.7:

```
root@ccbf59679e73:~# find /opt/puppetlabs/pdk/private/ruby/*/bin -type f -name 'pdk'
/opt/puppetlabs/pdk/private/ruby/2.4.10/bin/pdk
root@ccbf59679e73:~# ls -lad /opt/puppetlabs/pdk/private/ruby/*/bin
drwxr-xr-x 2 root root 4096 Feb 16 16:53 /opt/puppetlabs/pdk/private/ruby/2.4.10/bin
drwxr-xr-x 2 root root 4096 Feb 16 16:53 /opt/puppetlabs/pdk/private/ruby/2.5.8/bin
drwxr-xr-x 2 root root 4096 Feb 16 16:53 /opt/puppetlabs/pdk/private/ruby/2.7.2/bin
```

Installer script needs to be updated

### PR DESCRIPTION
**Pull request by cdenneen**
Fixes #18 #17 #16

### CODE REVIEW

**Comment by cdenneen** [comment]
This isn't working as there seems to be something wrong with running docker inside this image. This might need to be built `FROM docker:dind` as base? In order to do that however we'd need an `pdk` install for Alpine Linux.

**Comment by cdenneen** [comment]
This is working now. Was able to successfully provision with litmus inside a gitlab-ci pipeline.

**Comment by jpogran** [comment]
@cdenneen  Thank you for the PR! I'm in the midst of spooling up a new team that will be responsible for the Puppet developer experience, including tools like PDK and the container images we ship. This means we'll have a team dedicated to things like your PR again, but unfortunately this means it will take some time to get up to speed, so I can't review this PR immediately. What makes this PR wait for more review is committing to shipping a separate docker image. If you can split your PR into two, one for the onceover fix and a second one to introduce a new image I can test and merge the first and we can discuss the second.

**Comment by scotje** [comment]
Sorry, this got closed because we renamed the `master` branch to `main`. Feel free to open a new PR targeting the `main` branch.

**Pull request closed without merging**
